"""
Report generator for VCP screener results.
Produces both JSON and Markdown output files.
"""

import json
from datetime import datetime
from pathlib import Path


def generate_reports(results: list[dict], output_dir: str = "reports") -> dict:
    """
    Generate JSON and Markdown reports from screening results.

    Args:
        results: List of dicts, each containing screening data for one stock.
        output_dir: Directory to save reports.

    Returns:
        dict with json_path and md_path.
    """
    output_path = Path(output_dir)
    output_path.mkdir(parents=True, exist_ok=True)

    timestamp = datetime.now().strftime("%Y-%m-%d_%H%M%S")
    json_file = output_path / f"vcp_screener_{timestamp}.json"
    md_file = output_path / f"vcp_screener_{timestamp}.md"

    # Sort by composite score descending
    results.sort(key=lambda x: x.get("composite_score", 0), reverse=True)

    # JSON report
    report_data = {
        "generated_at": datetime.now().isoformat(),
        "total_screened": len(results),
        "results": results,
    }
    with open(json_file, "w") as f:
        json.dump(report_data, f, indent=2, default=str)

    # Markdown report
    md_content = _generate_markdown(results, timestamp)
    with open(md_file, "w") as f:
        f.write(md_content)

    return {
        "json_path": str(json_file),
        "md_path": str(md_file),
    }


def _generate_markdown(results: list[dict], timestamp: str) -> str:
    """Generate a human-readable Markdown report."""
    lines = [
        "# NSE VCP Screener Results",
        "",
        f"**Generated**: {timestamp}",
        f"**Candidates Found**: {len(results)}",
        "",
        "---",
        "",
    ]

    if not results:
        lines.append("No VCP candidates found matching the criteria.")
        return "\n".join(lines)

    # Summary table
    lines.extend([
        "## Top Candidates",
        "",
        "| Rank | Ticker | Price (₹) | Score | Quality | Pivot (₹) | Distance | Dry-Up | RS |",
        "|------|--------|-----------|-------|---------|-----------|----------|--------|----|",
    ])

    for i, r in enumerate(results[:20], 1):
        ticker = r.get("ticker", "?")
        price = r.get("price", 0)
        score = r.get("composite_score", 0)
        quality = r.get("quality", "?")
        pivot = r.get("pivot", 0)
        distance = r.get("pivot_distance_pct", 0)
        dry_up = r.get("dry_up_ratio", 0)
        rs = r.get("rs_value", 0)

        lines.append(
            f"| {i} | **{ticker}** | ₹{price:,.2f} | {score:.1f} | {quality} "
            f"| ₹{pivot:,.2f} | {distance:.1f}% | {dry_up:.2f} | {rs:+.1f}% |"
        )

    lines.append("")

    # Detailed analysis for top 10
    lines.extend(["---", "", "## Detailed Analysis", ""])

    for i, r in enumerate(results[:10], 1):
        ticker = r.get("ticker", "?")
        lines.extend([
            f"### {i}. {ticker} — Score: {r.get('composite_score', 0):.1f} ({r.get('quality', '?')})",
            "",
            f"- **Price**: ₹{r.get('price', 0):,.2f}",
            f"- **Pivot**: ₹{r.get('pivot', 0):,.2f} ({r.get('pivot_position', '?')})",
            f"- **Stage**: {r.get('stage', '?')}",
            f"- **Trend Score**: {r.get('trend_score', 0):.1f}/100",
            f"- **Contraction Score**: {r.get('contraction_score', 0):.1f}/100",
            f"- **Volume Dry-Up**: {r.get('dry_up_ratio', 0):.2f} (Score: {r.get('volume_score', 0):.1f})",
            f"- **Relative Strength**: {r.get('rs_value', 0):+.1f}% vs Nifty",
            "",
        ])

        contractions = r.get("contractions", [])
        if contractions:
            lines.append("**Contractions:**")
            for j, c in enumerate(contractions):
                label = f"T{j+1}"
                lines.append(
                    f"  - {label}: {c.get('depth_pct', 0):.1f}% depth over {c.get('duration_days', 0)} days"
                )
            lines.append("")

        lines.append("---")
        lines.append("")

    # Disclaimer
    lines.extend([
        "## Disclaimer",
        "",
        "This screening is based on technical pattern recognition and does not constitute investment advice. "
        "VCP patterns can fail. Always conduct your own due diligence, manage risk with stop-losses, "
        "and consider fundamental factors before trading. Past patterns do not guarantee future results.",
        "",
        "---",
        "*Generated by NSE VCP Screener — Indian Trading Skills*",
    ])

    return "\n".join(lines)
